restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('restaurant/', include('restaurantApp.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'), #obtener un token, despues de 5 minutos ya no funciona para hacer peticiones etc
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),# Refrescar el token, un token con un tiempo de vida mas largo
    path('', include('restaurantApp.urls')),
]

restaurantApp/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from restaurantApp.views import HomeView, CustomerViewSet, WaiterViewSet, ProductViewSet, TableViewSet, OrderViewSet, \
    InvoiceViewSet, CustomerCreateView, CustomerList, CustomerUpdateView, CustomerCanceled, \
    WaiterCreateView, WaiterList,WaiterUpdateView,WaiterCanceled,\
         ProductCreateView, ProductList, ProductUpdateView, ProductCanceled, \
            TableCreateView, TableList, TableUpdateView, TableCanceled, \
            OrderCreateView, OrderList, OrderUpdateView, OrderCanceled, \
            InvoiceCreateView, InvoiceList, InvoiceUpdateView, InvoiceCanceled

router = SimpleRouter()
router.register(r'customers', CustomerViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'waiters', WaiterViewSet)
router.register(r'products', ProductViewSet)
router.register(r'invoices', InvoiceViewSet)
router.register(r'tables', TableViewSet)

app_name = 'restaurantApp'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('customer_register/', CustomerCreateView.as_view(), name='customer_register'),
    path('customer_list/', CustomerList.as_view(), name='customer_list'),
    path('customer_update/<int:pk>/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customer_cancel/<int:pk>/', CustomerCanceled.as_view(), name='customer_cancel'),

    path('waiter_register/', WaiterCreateView.as_view(), name='waiter_register'),
    path('waiter_list/', WaiterList.as_view(), name='waiter_list'),
    path('waiter_update/<int:pk>/', WaiterUpdateView.as_view(), name='waiter_update'),
    path('waiter_cancel/<int:pk>/', WaiterCanceled.as_view(), name='waiter_cancel'),

    path('product_register/', ProductCreateView.as_view(), name='product_register'),
    path('product_list/', ProductList.as_view(), name='product_list'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_cancel/<int:pk>/', ProductCanceled.as_view(), name='product_cancel'),

    path('table_register/', TableCreateView.as_view(), name='table_register'),
    path('table_list/', TableList.as_view(), name='table_list'),
    path('table_update/<int:pk>/', TableUpdateView.as_view(), name='table_update'),
    path('table_cancel/<int:pk>/', TableCanceled.as_view(), name='table_cancel'),

    path('order_register/', OrderCreateView.as_view(), name='order_register'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('order_update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('order_cancel/<int:pk>/', OrderCanceled.as_view(), name='order_cancel'),

    path('invoice_register/', InvoiceCreateView.as_view(), name='invoice_register'),
    path('invoice_list/', InvoiceList.as_view(), name='invoice_list'),
    path('invoice_update/<int:pk>/', InvoiceUpdateView.as_view(), name='invoice_update'),
    path('invoice_cancel/<int:pk>/', InvoiceCanceled.as_view(), name='invoice_cancel'),
] + router.urls

templates/customer/create_customer.html
{% extends 'base.html' %}
{% block Title  %} Customer Register {% endblock %}
{% block content %}

    <div class="my-5 pt-1">
        <h2 class="my-4 text-center">Customer Register</h2>
        <div class="d-flex justify-content-center mb-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="">

                    <div class="d-flex row justify-content-center ">

                        <div class="">
                        </div>
                    </div>
                    {{ form.as_p }}

                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                    <div class="mt-3">
                        {% for field in form.visible_fields %}
                            <div class="form-group">

                                {% for error in field.errors %}
                                    <span class="help-block" style="color:red">{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/customer/delete_customer.html
{% extends 'base.html' %}
{% block title %} Cancel Customer {% endblock %}
{% block content %}'}

        <div class="d-flex justify-content-center">
            <form method="post" novalidate>
                {% csrf_token %}
                <h3>Are you sure you want to cancel Customer {{ customer.name }}?</h3>

                <div class="text-center mt-4">
                    <input value="Confirm" type="submit" class="btn btn-success text-center"/>
                </div>
            </form>
        </div>


{% endblock content %}'}

templates/customer/list_custom.html
{% extends 'base.html' %}
{% block content %}

        <div class="row mt-5 d-flex justify-content-center">

            <h2 class="text-center mb-5">Services Request List</h2>
            <div class="col-6">
                <table class="table caption-top">
                    <thead class="text-center">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">LAst Name</th>
                        <th scope="col">Observations</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in object_list %}
                        <tr class="text-center">

                            <td>{{ customer.name }}</td>
                            <td>{{ customer.last_name }}</td>
                            <td>{{ customer.observations }}</td>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>
{% endblock %}

templates/customer/update_customer.html
{% extends "base.html" %} {% block title %} Edit Customer
{% endblock %} {% block content %}


        <h2 class="text-center">Edit Customer</h2>

        <form method="post">
            {% csrf_token %} {% for field in form.visible_fields %}

            <div class="form-group">
                <div class="container">
                    <div class="col-6">
                        <label for="{{ field.id_for_label }}">{{ field.name }}</label>
                        {{ field }} {% for error in field.errors %}}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}

            <div class="container">
                <div class="col-6">
                    <button class="btn btn-success" type="submit">Submit</button>
                    <a href="{% url 'restaurantApp:home' %}" class="btn btn-primary">Cancel</a>
                </div>
            </div>
        </form>

{% endblock %}